# Generated by Django 3.1.7 on 2021-07-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210721_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255, verbose_name='full_name'),
        ),
    ]
