# Generated by Django 3.1.7 on 2022-02-23 06:51

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0002_auto_20220212_0708'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=355)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(help_text='If left blank, it will be created automatically', max_length=10, unique=True)),
                ('value', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField()),
                ('user_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=225), blank=True, null=True, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('order_id', models.CharField(max_length=30)),
                ('payment_method', models.CharField(max_length=30)),
                ('delivery_method', models.CharField(max_length=30)),
                ('delivery_status', models.CharField(default='Order in progress', max_length=30)),
                ('closed', models.BooleanField(default=False)),
                ('coupon', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=225), blank=True, null=True, size=None)),
                ('paid', models.BooleanField(default=False)),
                ('order_price', models.PositiveBigIntegerField(default=0)),
                ('order_price_total', models.PositiveBigIntegerField(default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('cart_items', models.ManyToManyField(related_name='order_cart_items', to='market.CartItem')),
                ('door_step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.billing')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount', models.FloatField(default=0)),
                ('ref', models.CharField(max_length=200)),
                ('user_id', models.CharField(default=None, max_length=225)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(default='admin', max_length=225)),
                ('phone', models.CharField(default='+1809384583', max_length=15)),
                ('description', models.CharField(default='Purchase goods', max_length=225)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('verified', models.BooleanField(default=False)),
                ('redirect_url', models.URLField(default='https://kwekmarket.com/')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-transaction_date',),
            },
        ),
        migrations.CreateModel(
            name='Pickup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=355)),
                ('state', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('progress', models.CharField(default='Order Placed', max_length=30)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='bill.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='pickup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bill.pickup'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CouponUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='bill.coupon')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('coupon', 'user')},
            },
        ),
    ]
