# Generated by Django 3.1.7 on 2022-02-12 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('customer_name', models.CharField(max_length=225)),
                ('customer_email', models.EmailField(default='', max_length=254)),
                ('customer_address', models.CharField(max_length=225)),
                ('delivery_fee', models.PositiveBigIntegerField()),
                ('subtotal', models.PositiveBigIntegerField()),
                ('total', models.PositiveBigIntegerField()),
                ('invoice_number', models.CharField(max_length=10)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('balance', models.PositiveBigIntegerField(default=0)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('remark', models.CharField(max_length=225)),
                ('amount', models.PositiveBigIntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=False)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='wallet.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='StoreDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('store_name', models.CharField(error_messages={'unique': 'Store with name already exists'}, max_length=225, unique=True)),
                ('email', models.EmailField(error_messages={'unique': 'Store with email already exists'}, max_length=254, unique=True)),
                ('address', models.CharField(max_length=225)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('item', models.CharField(max_length=225)),
                ('description', models.TextField(default='')),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('unit_cost', models.PositiveBigIntegerField()),
                ('total', models.PositiveBigIntegerField()),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_item', to='wallet.invoice')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.storedetail'),
        ),
    ]
