# Generated by Django 3.1.7 on 2021-10-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=255)),
                ('height', models.IntegerField(default=None)),
                ('width', models.IntegerField(default=None)),
                ('extension', models.CharField(max_length=255)),
                ('asset_type', models.CharField(max_length=255)),
            ],
        ),
    ]
